[PatchNote.Maker]
Directory = "ChangeLog.d"
OutputFileName = "CHANGELOG.md"
TemplateFilePath = "Template.tt"

[[PatchNote.Section]]
Path = ""
DisplayName = "Main"

[[PatchNote.Section]]
Path = "A"
DisplayName = "A Section"

[[PatchNote.Section]]
Path = "B"
DisplayName = "B Section"

[[PatchNote.Type]]
Category = "security"
DisplayName = "Security"
IsShowContent = true

[[PatchNote.Type]]
Category = "removed"
DisplayName = "Removed"
IsShowContent = true

[[PatchNote.Type]]
Category = "deprecated"
DisplayName = "Deprecated"
IsShowContent = true

[[PatchNote.Type]]
Category = "added"
DisplayName = "Added"
IsShowContent = true

[[PatchNote.Type]]
Category = "changed"
DisplayName = "Changed"
IsShowContent = true

[[PatchNote.Type]]
Category = "fixed"
DisplayName = "Fixed"
IsShowContent = true
