name: .NET Test Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'NF.Tool.ReleaseNoteMaker/**'
  pull_request:
    branches:
      - main
    paths:
      - 'NF.Tool.ReleaseNoteMaker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Run tests
        working-directory: NF.Tool.ReleaseNoteMaker
        run: dotnet test --configuration Release --verbosity normal
